apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: ci-artifacts
  name: "{{ build_operand_imagestream_name }}"
  namespace: "{{ build_operand_namespace }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ build_operand_imagestream_name }}:latest"
      namespace: "{{ build_operand_namespace }}"
  resources: {}
  source:
    type: Git
    git:
      uri: "{{ build_operand_git_repo }}"
      ref: "{{ build_operand_git_ref }}"
    contextDir: .
  triggers:
  - type: "ConfigChange"
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: "VERSION"
          value: "v0.1.0"
        - name: "GOLANG_VERSION"
          value: "1.15"
        - name: "BASE_IMAGE"
          value: "nvcr.io/nvidia/cuda:11.2.1-base-ubi8"
        - name: "CUDA_SAMPLE_IMAGE"
          value: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.2.1-ubi8"
      dockerfilePath: validator/Dockerfile
