apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: ci-artifacts
  name: "{{ build_operand_imagestream_name }}"
  namespace: "{{ build_operand_namespace }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ build_operand_imagestream_name }}:latest-rhcos4.7"
      namespace: "{{ build_operand_namespace }}"
  resources: {}
  source:
    type: Git
    git:
      uri: "{{ build_operand_git_repo }}"
      ref: "{{ build_operand_git_ref }}"
    contextDir: .
  triggers:
  - type: "ConfigChange"
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: "BASE_DIST"
          value: "ubi8"
        - name: "CUDA_VER"
          value: "11.2.1"
        - name: "SAMPLE_NAME"
          value: "vectorAdd"
      dockerfilePath: cuda/Dockerfile.ubi8
