apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: ci-artifacts
  name: image-builder
  namespace: "{{ build_image_namespace }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: dcgm-exporter:latest-rhcos4.7
      namespace: "{{ build_image_namespace }}"
  resources: {}
  source:
    type: Git
    git:
      uri: "{{ build_image_git_repo }}" # set by `build.yaml` ansible script
      ref: "{{ build_image_git_ref }}" # set by `build.yaml` ansible script
    contextDir: .
  triggers:
  - type: "ConfigChange"
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: "GOLANG_VERSION"
          value: "1.14.2"
        - name: "DCGM_VERSION"
          value: "2.1.8"
        - name: "VERSION"
          value: "2.4.0-rc.2"
      dockerfilePath: docker/Dockerfile.ubi8
