apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: ci-artifacts
  name: "{{ build_operand_imagestream_name }}"
  namespace: "{{ build_operand_namespace }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ build_operand_imagestream_name }}:latest"
      namespace: "{{ build_operand_namespace }}"
  resources: {}
  source:
    type: Git
    git:
      uri: "{{ build_operand_git_repo }}"
      ref: "{{ build_operand_git_ref }}"
    contextDir: .
  triggers:
  - type: "ConfigChange"
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: "GOLANG_VERSION"
          value: "1.14.2"
        - name: "DCGM_VERSION"
          value: "2.1.8"
        - name: "VERSION"
          value: "2.4.0-rc.2"
      dockerfilePath: docker/Dockerfile.ubi8
