---
- name: "Ensure that the entitlement file 'entitlement_pem={{ entitlement_pem }}' exists"
  stat:
    path: '{{ entitlement_pem }}'
  register: entitlement_pem_stat
  failed_when: not entitlement_pem_stat.stat.exists

- name: "Ensure that the entitlement RHSM file 'entitlement_rhsm={{ entitlement_rhsm }}' exists"
  stat:
    path: '{{ entitlement_rhsm }}'
  register: entitlement_rhsm_stat
  failed_when: not entitlement_rhsm_stat.stat.exists

- name: "Deploy RHSM from file '{{ entitlement_rhsm }}'"
  shell:
    set -o pipefail;
    python3 "{{ entitlement_py_apply }}"
            "{{ entitlement_mc_rhsm }}" BASE64_ENCODED_RHSM_FILE "{{ entitlement_rhsm }}"
      | oc create -f-

- name: "Deploy the pem and key-pem from file '{{ entitlement_pem }}'"
  shell:
    set -o pipefail;
    python3 "{{ entitlement_py_apply }}"
            "{{ entitlement_mc_pem }}" BASE64_ENCODED_PEM_FILE "{{ entitlement_pem }}"
      | oc create -f-
