---
- name: Make sure imagestream name is set
  when: not build_operand_imagestream_name
  fail: msg="Failed because build_operand_imagestream_name has to be set"

- name: Apply the namespace manifest
  shell:
    set -o pipefail;
    cat "{{ build_operand_namespace_deployment }}" \
     | sed 's|{{ '{{' }} build_operand_namespace {{ '}}' }}|{{ build_operand_namespace }}|' \
     | oc apply -f-

- name: Apply the imagestream manifest
  shell:
    set -o pipefail;
    cat "{{ build_operand_imagestream }}" \
     | sed 's|{{ '{{' }} build_operand_namespace {{ '}}' }}|{{ build_operand_namespace }}|' \
     | sed 's|{{ '{{' }} build_operand_imagestream_name {{ '}}' }}|{{ build_operand_imagestream_name }}|' \
     | oc apply -f-
