---
gpu_operator_git_repo: ""
gpu_operator_git_ref: ""
gpu_operator_image_tag_uid: ""
gpu_operator_image_tag: "gpu-operator-{{ gpu_operator_image_tag_uid }}"
gpu_operator_bundle_image_tag: "gpu-operator-bundle-{{ gpu_operator_image_tag_uid }}"
gpu_operator_alm_examples_patch_file: ""
gpu_operator_csv_semver: "9.9.9"
