---
- name: Search if the CI image exists
  command: oc get imagestreamtag -n "{{ build_image_namespace }}" "driver:latest-rhcos4.7" -oname --ignore-not-found
  register: has_ci_image

- name: Build the CI image
  when: has_ci_image.stdout == ""
  block:
  - name: Delete any old image builder manifest
    command: oc delete -f "{{ build_image_image_builder }}" --ignore-not-found

  - name: Apply the CI artifacts image builder manifest
    shell:
      set -o pipefail;
      cat "{{ build_image_image_builder }}" \
       | sed 's|{{ '{{' }} build_image_namespace {{ '}}' }}|{{ build_image_namespace }}|' \
       | sed 's|{{ '{{' }} build_image_git_repo {{ '}}' }}|{{ build_image_git_repo }}|' \
       | sed 's|{{ '{{' }} build_image_git_ref {{ '}}' }}|{{ build_image_git_ref }}|' \
       | oc apply -f-
    args:
      warn: false # don't warn about using sed here

  - name: Wait for the image to be built
    shell: oc logs -f buildconfig/image-builder -n {{ build_image_namespace }} > /dev/null

- name: Ensure that the image exists
  command: oc get imagestreamtag -n "{{ build_image_namespace }}" \
    "latest-rhcos4.7" -oname --ignore-not-found
